### ISSUE TITLE
[Front] HU13 - T13.08 - Crear formulario Reserva

### ISSUE THREAD

**Issue by jolomoreno** [mdw-agiles/pr-mdw-agiles-front#1]
- Tarea 8 -  [FRONT] Realizar formulario de reserva de habitación. Los campos a rellenar serán: Cadena de hotel (select), Hotel (select), Habitación(select), Dia/Mes/Año(datepicker), Hora(select con horas. 09:00, 10:00...) y Tiempo de Reserva(input number).

- Tiempo dedicado: 20h

**Comment by alexph9** [comment]
Done
